global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'ipmi_exporter'
    static_configs:
      - targets: ['localhost:9290']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
 
