{
 "title": "first",
 "time": { "from": "2024-07-15T11:38:54.789Z", "to": "2024-07-15T14:03:08.525Z" },
 "panels": [
  {
   "title": "Total_CPU_Power_Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\"}[5m])) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " NIC_Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_Idle_Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average_CPU_Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 1\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total_CPU_Utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Full_Energy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_power_supply_energy_full{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_Seconds_Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_info{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Energy_Watthr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_power_supply_energy_watthour{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "node_power_supply_online{power_supply=\"AC1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Present",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_present{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "node_power_supply_power_watt{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Cap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "node_power_supply_capacity{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power_Supply_Cycle_Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "node_power_supply_cyclecount{power_supply=\"BAT1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active_Bytes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(instance) (node_memory_Active_bytes{instance=\"localhost:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGP_Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "node_vmstat_pgpgout{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGP_In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "node_vmstat_pgpgin{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem_Total_Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem_Free_Bytes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}